### ISSUE TITLE
line.split error

### ISSUE THREAD

**Issue by torrmundi** [nootropicdesign/node-red-contrib-nmea#1]
I got this error:
TypeError: line.split is not a function
RPI4B, v11 (bullseye), with Node Red v2.2.0. Data was from a boat's N2K network via a Yacht Devices YDWG02 converter.

**Comment by nootropicdesign** [comment]
Please tell us what input you are sending into the node. Otherwise there is no way to know what is wrong.

**Comment by torrmundi** [comment]
I've found the error (on my part). I used a UDP stream without specifying it to be strings. Please ignore my comment.

**Comment by nootropicdesign** [comment]
Thanks, closing.
